version: '3.2'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./services/node_web/Dockerfile
    volumes:
      - ./:/home/www:cached
    ports:
      - 81:3000
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
volumes:
  mongo-data: