version: '3.2'

services:
  web:
    container_name: web
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/home/www:cached
    ports:
      - 81:3000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
volumes:
  mongo-data:
