version: '3.2'

x-default-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '5m'
    max-file: '1'

services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 81:80
  logging: *default-logging
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - .:/home/www:cached
    restart: always
  logging: *default-logging
#  cron:
#    build:
#      context: ./services/cron
#      dockerfile: Dockerfile
#    volumes:
#      - .:/home/www:cached
#  likes-consumer:
#    build:
#      context: ./services/likesConsumer
#      dockerfile: Dockerfile
#    stop_grace_period: 20s
#    volumes:
#      - .:/home/www:cached
#    restart: always
#    ports:
#      - 9229:9229
#      - 8147:8147
#      - 80:80
  rabbit:
    image: rabbitmq:3-management
    volumes:
      - rabbit-data:/var/lib/rabbitmq:cached
    logging:
      driver: none
    ports:
      - 8081:15672
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
volumes:
  mongo-data:
  rabbit-data:
