version: '2.2'

x-default-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '5m'
    max-file: '1'


services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 81:80
    volumes:
      - /dev/null:/var/log/nginx/access.log
    logging: *default-logging
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/web/public:/home/www:cached
      - /dev/null:/var/log/nginx/access.log
    logging: *default-logging
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/www:cached
    restart: always
    logging: *default-logging
  cron:
    build:
      context: ./services/cron
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/www:cached
  rabbit:
    image: rabbitmq:3-management
    volumes:
      - rabbit-data:/var/lib/rabbitmq:cached
    logging:
      driver: none
    env_file:
      - .env
    ports:
      - 8081:15672
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
volumes:
  mongo-data:
  rabbit-data:
