version: '3.2'

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - .:/home/www:cached
    ports:
      - 81:3000
#  cron:
#    build:
#      context: ./services/cron
#      dockerfile: Dockerfile
#    volumes:
#      - .:/home/www:cached
  task-consumer:
    build:
      context: ./services/taskConsumer
      dockerfile: Dockerfile
    stop_grace_period: 20s
    volumes:
      - .:/home/www:cached
    restart: always
  rabbit:
    image: rabbitmq:3-management
    volumes:
      - rabbit-data:/var/lib/rabbitmq:cached
    logging:
      driver: none
    ports:
      - 8081:15672
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
volumes:
  mongo-data:
  rabbit-data:
