version: '3.2'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/home/www:cached
    ports:
      - 81:3000
  task-consumer:
    build:
      context: ./taskConsumer
      dockerfile: Dockerfile
    volumes:
      - ./taskConsumer:/home/www:cached
  rabbit:
    image: rabbitmq
    volumes:
      - rabbit-data:/var/lib/rabbitmq:cached
    logging:
      driver: none
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
volumes:
  mongo-data:
  rabbit-data:
