// flow-typed signature: 011d4aabe214f8d46abcad423223084e
// flow-typed version: <<STUB>>/bunyan-debug-stream_v^1.0.8/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bunyan-debug-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bunyan-debug-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bunyan-debug-stream/lib/BunyanDebugStream' {
  declare module.exports: any;
}

declare module 'bunyan-debug-stream/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bunyan-debug-stream/lib/BunyanDebugStream.js' {
  declare module.exports: $Exports<'bunyan-debug-stream/lib/BunyanDebugStream'>;
}
declare module 'bunyan-debug-stream/lib/utils.js' {
  declare module.exports: $Exports<'bunyan-debug-stream/lib/utils'>;
}
