# prometheus.yml
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'rabbit-exporter'
    static_configs:
      - targets: ['rabbit-exporter:9090']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9913']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
