actions:
  1:
    action: delete_indices
    description: >-
      Delete logstash indices older than 30 days.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: fluentd-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y%m%d'
      unit: days
      unit_count: 5
      exclude:
